# Generated by Django 2.2.6 on 2019-10-25 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0004_auto_20191025_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drug',
            name='uniprot_id',
            field=models.CharField(max_length=1000),
        ),
    ]
