# Generated by Django 2.2.6 on 2019-10-25 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0005_auto_20191025_1729'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drug2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uniprot_id', models.CharField(default='', max_length=1000)),
            ],
        ),
        migrations.RemoveField(
            model_name='drug',
            name='uniprot_id',
        ),
    ]
