# Generated by Django 2.2.6 on 2019-10-25 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0006_auto_20191025_1736'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Drug2',
        ),
        migrations.AddField(
            model_name='drug',
            name='uniprot_id',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
