# Generated by Django 2.2.6 on 2019-10-25 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0010_auto_20191025_2039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drug',
            name='pubmed_id',
        ),
    ]
