# Generated by Django 2.2.6 on 2019-10-25 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0011_remove_drug_pubmed_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='drug',
            name='annotated',
            field=models.CharField(default='-', max_length=1000, null=True),
        ),
    ]
