# Generated by Django 2.2.6 on 2019-10-25 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0018_auto_20191025_2227'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='drug',
            unique_together={('activity_comment', 'annotated', 'annotation_comments', 'compound_name', 'uniprot_id')},
        ),
    ]
