# Generated by Django 2.2.6 on 2019-10-27 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0025_auto_20191026_1911'),
    ]

    operations = [
        migrations.AddField(
            model_name='drug',
            name='assay_cell_type',
            field=models.CharField(default='-', max_length=25500, null=True),
        ),
    ]
