# Generated by Django 2.2.6 on 2019-10-29 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0028_auto_20191027_2317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drug',
            name='compound_concetration_value_unit',
        ),
        migrations.RemoveField(
            model_name='drug',
            name='compound_name',
        ),
        migrations.RemoveField(
            model_name='drug',
            name='detection_technology',
        ),
        migrations.RemoveField(
            model_name='drug',
            name='endpoint_actionmode',
        ),
        migrations.RemoveField(
            model_name='drug',
            name='endpoint_standard_relation',
        ),
        migrations.RemoveField(
            model_name='drug',
            name='endpoint_standard_type',
        ),
        migrations.RemoveField(
            model_name='drug',
            name='endpoint_standard_units',
        ),
        migrations.RemoveField(
            model_name='drug',
            name='endpoint_standard_value',
        ),
        migrations.RemoveField(
            model_name='drug',
            name='gene_name',
        ),
        migrations.RemoveField(
            model_name='drug',
            name='inhibitor_type',
        ),
        migrations.RemoveField(
            model_name='drug',
            name='max_phase',
        ),
        migrations.RemoveField(
            model_name='drug',
            name='mutation_info',
        ),
        migrations.RemoveField(
            model_name='drug',
            name='protein_class',
        ),
        migrations.RemoveField(
            model_name='drug',
            name='pubmed_id',
        ),
        migrations.RemoveField(
            model_name='drug',
            name='resource_uri',
        ),
        migrations.RemoveField(
            model_name='drug',
            name='target_organism',
        ),
        migrations.RemoveField(
            model_name='drug',
            name='target_pref_name',
        ),
        migrations.RemoveField(
            model_name='drug',
            name='uniprot_id',
        ),
        migrations.RemoveField(
            model_name='drug',
            name='wildtype_or_mutant',
        ),
    ]
