# Generated by Django 2.2.6 on 2019-10-30 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0030_auto_20191029_1058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drug',
            name='activity_comment',
        ),
        migrations.RemoveField(
            model_name='drug',
            name='annotated',
        ),
        migrations.RemoveField(
            model_name='drug',
            name='annotation_comments',
        ),
        migrations.RemoveField(
            model_name='drug',
            name='assay_cell_type',
        ),
        migrations.RemoveField(
            model_name='drug',
            name='assay_format',
        ),
        migrations.RemoveField(
            model_name='drug',
            name='assay_sub_type',
        ),
        migrations.RemoveField(
            model_name='drug',
            name='assay_type',
        ),
        migrations.RemoveField(
            model_name='drug',
            name='chembl_id',
        ),
        migrations.RemoveField(
            model_name='drug',
            name='compound_concetration_value',
        ),
        migrations.RemoveField(
            model_name='drug',
            name='compound_concetration_value_unit',
        ),
        migrations.RemoveField(
            model_name='drug',
            name='detection_technology',
        ),
        migrations.RemoveField(
            model_name='drug',
            name='endpoint_actionmode',
        ),
        migrations.RemoveField(
            model_name='drug',
            name='endpoint_standard_relation',
        ),
        migrations.RemoveField(
            model_name='drug',
            name='endpoint_standard_type',
        ),
        migrations.RemoveField(
            model_name='drug',
            name='endpoint_standard_units',
        ),
        migrations.RemoveField(
            model_name='drug',
            name='endpoint_standard_value',
        ),
        migrations.RemoveField(
            model_name='drug',
            name='inhibitor_type',
        ),
        migrations.RemoveField(
            model_name='drug',
            name='max_phase',
        ),
        migrations.RemoveField(
            model_name='drug',
            name='mutation_info',
        ),
        migrations.RemoveField(
            model_name='drug',
            name='protein_class',
        ),
        migrations.RemoveField(
            model_name='drug',
            name='resource_uri',
        ),
        migrations.RemoveField(
            model_name='drug',
            name='target_organism',
        ),
        migrations.RemoveField(
            model_name='drug',
            name='uniprot_id',
        ),
        migrations.RemoveField(
            model_name='drug',
            name='wildtype_or_mutant',
        ),
    ]
