# Generated by Django 2.2.6 on 2019-10-30 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0031_auto_20191030_1152'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='drug',
            unique_together={('compound_name', 'authors', 'gene_name', 'pubmed_id', 'target_pref_name')},
        ),
    ]
