# Generated by Django 2.2.6 on 2019-10-30 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0032_auto_20191030_1504'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='drug',
            constraint=models.CheckConstraint(check=models.Q(compound_name__gte=10), name='compound_name'),
        ),
    ]
