# Generated by Django 2.2.6 on 2019-11-02 17:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0034_auto_20191030_2147'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compound',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chembl_id', models.CharField(default='', max_length=25500, null=True)),
                ('compound_name', models.CharField(max_length=25500, null=True, validators=[django.core.validators.RegexValidator(code='invalid_language', message='Invalid Language! Please insert values in English', regex='^[a-zA-Z]*$')])),
                ('_change', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Publications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pubmed_id', models.CharField(default='', max_length=25500, null=True, validators=[django.core.validators.RegexValidator(code='invalid_character', message='Invalid Characters! Please insert number', regex='^[0-9]*$')])),
                ('authors', models.CharField(default='', max_length=25500, null=True, validators=[django.core.validators.RegexValidator(code='invalid_language', message='Invalid Language! Please insert values in English', regex='^[a-zA-Z]*$')])),
                ('_change', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('gene_name', models.CharField(default='', max_length=25500, null=True, validators=[django.core.validators.RegexValidator(code='invalid_character', message='Invalid Characters! Please only characters', regex='^[a-zA-Z]*$')])),
                ('uniprot_id', models.CharField(default='', max_length=25500, null=True, validators=[django.core.validators.RegexValidator(code='invalid_Characters', message='Invalid Characters! Please characters and numbers', regex='^[A-Z0-9]*$')])),
                ('target_pref_name', models.CharField(default='', max_length=25500, null=True, validators=[django.core.validators.RegexValidator(code='invalid_Characters', message='Invalid Characters! Please characters and numbers', regex='^[A-Z0-9]*$')])),
                ('_change', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='Drug',
        ),
    ]
