# Generated by Django 2.2.6 on 2019-11-02 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0035_auto_20191102_1743'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Compound',
        ),
        migrations.DeleteModel(
            name='Target',
        ),
    ]
