# Generated by Django 2.2.6 on 2019-11-03 17:50

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0037_compound_target'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compound',
            name='_change',
        ),
        migrations.RemoveField(
            model_name='publications',
            name='_change',
        ),
        migrations.AddField(
            model_name='compound',
            name='target',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='drugs.Target'),
        ),
        migrations.AddField(
            model_name='target',
            name='publication',
            field=models.ManyToManyField(to='drugs.Publications'),
        ),
        migrations.AlterField(
            model_name='compound',
            name='compound_name',
            field=models.CharField(max_length=25500, null=True, validators=[django.core.validators.RegexValidator(code='invalid_language', message='Please insert values in English', regex='^[a-zA-Z]*$')]),
        ),
    ]
