# Generated by Django 2.2.6 on 2019-11-03 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0038_auto_20191103_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compound',
            name='target',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='drugs.Target'),
        ),
    ]
