# Generated by Django 2.2.6 on 2019-11-03 21:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0040_auto_20191103_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publications',
            name='authors',
            field=models.CharField(default='', max_length=25500, validators=[django.core.validators.RegexValidator(code='invalid_language', message='Invalid Language! Please insert values in English', regex='^[a-zA-Z]*$')]),
        ),
    ]
