# Generated by Django 2.2.6 on 2019-11-03 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0042_auto_20191103_2134'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='compound',
            constraint=models.UniqueConstraint(fields=('compound_name', 'chembl_id'), name='avoid_duplications_compound'),
        ),
        migrations.AddConstraint(
            model_name='publications',
            constraint=models.UniqueConstraint(fields=('pubmed_id', 'authors'), name='avoid_duplications'),
        ),
        migrations.AddConstraint(
            model_name='target',
            constraint=models.UniqueConstraint(fields=('uniprot_id', 'target_pref_name', 'gene_name'), name='avoid_duplications_target'),
        ),
    ]
