# Generated by Django 2.2.6 on 2019-11-03 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0043_auto_20191103_2221'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='compound',
            name='avoid_duplications_compound',
        ),
        migrations.RemoveConstraint(
            model_name='publications',
            name='avoid_duplications',
        ),
        migrations.RemoveConstraint(
            model_name='target',
            name='avoid_duplications_target',
        ),
    ]
