# Generated by Django 2.2.6 on 2019-11-04 20:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0044_auto_20191103_2228'),
    ]

    operations = [
        migrations.AddField(
            model_name='compound',
            name='_change',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='publications',
            name='_change',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='publications',
            name='authors',
            field=models.CharField(default='', max_length=25500, null=True, validators=[django.core.validators.RegexValidator(code='invalid_language', message='Invalid Language! Please insert values in English', regex='^[a-zA-Z,.]*$')]),
        ),
        migrations.AlterField(
            model_name='target',
            name='target_pref_name',
            field=models.CharField(default='', max_length=25500, null=True, validators=[django.core.validators.RegexValidator(code='invalid_Characters', message='Invalid Characters! Please characters and numbers', regex='^[a-zA-Z0-9]*$')]),
        ),
    ]
